events {}

http {
    server {
        listen 80;

        location / {
            set $auth_header $http_authorization;
            if ($auth_header !~* "^Bearer YOUR_BEARER_TOKEN$") {
                return 401;
            }
            proxy_pass http://api:3002;
        }
    }
}